In [1]:
from part_I import transition
import numpy as np

Layout [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Circle = False
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
Expected number of turns : 6.6674
Layout [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Circle = True
[2. 2. 2. 2. 2. 2. 2. 2. 1. 0. 2. 2. 2. 1.]
Expected number of turns : 9.0564
Layout [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.] Circle = False
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Expected number of turns : 17.0000
Layout [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.] Circle = True
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 2. 2. 2. 1.]
Expected number of turns : 26.3333
Layout [0. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 0.] Circle = False
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Expected number of turns : 17.0000
Layout [0. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 0.] Circle = True
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 2. 2. 1.]
Expected number of turns : 25.3333
Layout [0. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 0.] Circle = False
[1. 0. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
Expe

In [76]:


layout = np.ones(15)*4
layout[0] = 0
layout[14] = 0

circle = True

state = (13, 0)
action = 2
for i in range(5): print(transition(state, action,layout, circle))

(0, False)
(0, False)
(2, True)
(1, True)
(0, False)
